RISC-V: cpufeature: fix broken merge of stable
The merge of stable was completely botched and not even build
tested, producing a rake of issues:
arch/riscv/kernel/cpufeature.c:319:8: error: call to undeclared function 'PATCH_ID_CPUFEATURE_ID'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                id = PATCH_ID_CPUFEATURE_ID(alt->patch_id);
                     ^
arch/riscv/kernel/cpufeature.c:319:36: error: no member named 'patch_id' in 'struct alt_entry'
                id = PATCH_ID_CPUFEATURE_ID(alt->patch_id);
                                            ~~~  ^
arch/riscv/kernel/cpufeature.c:329:11: error: call to undeclared function 'PATCH_ID_CPUFEATURE_VALUE'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                value = PATCH_ID_CPUFEATURE_VALUE(alt->patch_id);
                        ^
arch/riscv/kernel/cpufeature.c:329:42: error: no member named 'patch_id' in 'struct alt_entry'
                value = PATCH_ID_CPUFEATURE_VALUE(alt->patch_id);
                                                  ~~~  ^
arch/riscv/kernel/cpufeature.c:330:8: error: call to undeclared function 'riscv_cpufeature_patch_check'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                if (!riscv_cpufeature_patch_check(id, value))
                     ^
arch/riscv/kernel/cpufeature.c:330:8: note: did you mean 'riscv_cpufeature_patch_func'?
arch/riscv/kernel/cpufeature.c:304:23: note: 'riscv_cpufeature_patch_func' declared here
void __init_or_module riscv_cpufeature_patch_func(struct alt_entry *begin,
                      ^
arch/riscv/kernel/cpufeature.c:333:12: error: call to undeclared function 'ALT_OLD_PTR'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                oldptr = ALT_OLD_PTR(alt);
                         ^
arch/riscv/kernel/cpufeature.c:333:10: error: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Wint-conversion]
                oldptr = ALT_OLD_PTR(alt);
                       ^ ~~~~~~~~~~~~~~~~
arch/riscv/kernel/cpufeature.c:334:12: error: call to undeclared function 'ALT_ALT_PTR'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                altptr = ALT_ALT_PTR(alt);
                         ^
arch/riscv/kernel/cpufeature.c:334:10: error: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Wint-conversion]
                altptr = ALT_ALT_PTR(alt);
                       ^ ~~~~~~~~~~~~~~~~
9 errors generated.

This appears to have happened because riscv_cpufeature_patch_func() was
taken from mainline, rather than the correct merge conflict resolution,
which was to simply take the lock/unlock from stable & call to
riscv_alternative_fix_offsets() from our branch.

Fixes: d1223f817ce5 ("Merge branch 'stable/linux-6.1.y' into linux-6.1-mchp")
Signed-off-by: Conor Dooley <conor.dooley@microchip.com>