Revert "dma-buf: Use seqlock_t instread disabling preemption"
This reverts commit e8d6bbfe5dfc7b28e8cab2c1d322a0d47700019e.
This commit caused the PVR on RT to compile break.

Reverting until commit can be applied to both TI parent and TI RT branch
as well as a fix to the PVR code.

pvr_linux_fence.c:1003:28: error: passing argument 1 of 'read_seqcount_begin'
from incompatible pointer type [-Werror=incompatible-pointer-types]

Signed-off-by: Dan Murphy <dmurphy@ti.com>