pwm: microchip-core: fix build after stable merge
The build of the stable merge was not tested, resulting in a build
failure:
./drivers/pwm/pwm-microchip-core.c:378:15: error: incompatible function pointer types initializing 'int (*)(struct pwm_chip *, struct pwm_device *, struct pwm_state *)' with an expression of type 'void (struct pwm_chip *, struct pwm_device *, struct pwm_state *)' [-Wincompatible-function-pointer-types]
        .get_state = mchp_core_pwm_get_state,
                     ^~~~~~~~~~~~~~~~~~~~~~~

Change the signature to fix the build.

Fixes: d1223f817ce5 ("Merge branch 'stable/linux-6.1.y' into linux-6.1-mchp")
Signed-off-by: Conor Dooley <conor.dooley@microchip.com>