dt-bindings: phy: microchip,sama7-utmi-clk: repair bindings example
Running dt_binding_check with this binding in the tree fails:
Error: Documentation/devicetree/bindings/phy/microchip,sama7-utmi-clk.example.dts:27.39-40 syntax error
FATAL ERROR: Unable to parse input tree

Add the missing SAMA7G5 prefix to the defines in the example so that
dt_binding_check is usable once more.

Fixes: 8c5fc1b4ff4d ("phy: microchip: add driver for sama7 USB 2.0 PHY")
Signed-off-by: Conor Dooley <conor.dooley@microchip.com>
Acked-by: Cristian Birsan <cristian.birsan@microchip.com>